### ISSUE TITLE
deprecate in favor of mapbox-cli?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-dataset-cli#12]
@jakepruitt @perrygeo does mapbox-cli cover all the functionality of this? can we move this to cutting-room-floor?

**Comment by perrygeo** [comment]
The currently implementation in `mapbox-cli-py` covers the datasets API fully so I would say yes. Some caveats:
- The `mapbox datasets` interface and command names match the API endpoints closely so they're slightly different than mapbox-data (no big deal, just not a drop-in replacement)
- We're currently working through a [higher-level interface](https://github.com/mapbox/mapbox-cli-py/pull/39) that will feel more like `aws s3` - there is still an ongoing discussion around how these two styles of interface should co-exist
- Several people are having difficulties installing it globally due to version conflicts with system python libs. This means we'll need to focus on [packaging and distribution](https://github.com/mapbox/mapbox-cli-py/issues/18) soon

cc @rclark @sgillies
